name: chitchat
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.3+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.3
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  go_router: ^14.8.0
  email_validator: ^3.0.0
  fluttertoast: ^8.2.12
  intl: ^0.19.0
  flutter_slidable: ^4.0.0
  dotted_border: ^2.1.0
  shared_preferences: ^2.5.2
  flutter_native_splash: ^2.4.4
  image_picker: ^1.1.2
  video_player: ^2.9.3
  get_thumbnail_video: ^0.7.3
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.9.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/background/
    - assets/icons/
  
  fonts:
    - family: Caros
      fonts:
        - asset: assets/fonts/caros/Caros Bold.otf
        - asset: assets/fonts/caros/Caros Medium.otf
        - asset: assets/fonts/caros/Caros Italic.otf
          style: italic
    - family: circular
      fonts:
        - asset: assets/fonts/circular_std/circular-std-medium-500.ttf
